language: cpp
sudo: true
compiler:
  - gcc
env:
  global:
    secure: "ICHCfGL89H8/J6Z34o2bw9VozkXFdKvktVyAhETkkIVcdoT+8V2a+4+Sl5hfIxpw1grhgcqFmjTdWb6K40peaA7hbTG+CTkI0Le0NhFqzwH7AiyWat1LY1lu0wdPf9QukjNAlgGgOy3f59Sw48AgtEFxqFt6Uwj8pOCdHjXZUY8fRVomJl6oqdvPP+Lfm4Ug5v8CZVDS1xLMz3ciNfh8c6mOfaLX6LP97GM35/Q37KhHjZKNqncfigL+X5Cmr3Rw/Xtno2XEl7eIaQ9YxVchUUxqJU+mTtdm13KYShohtro1Ue/sXtcLSwYP/7fPmtQBMfmXMVrY0FR3lLRwBTjJwx4Es7m2dOqIDs88Vl4xvsow+zBWWMjMpZniGWzE56PR+a12RjUjEQbnqhygiQKcdY1Qp//R+0kpTNiFpIXy9BzwD9mMwnd/2EI0tbjI+wsU2wwIIGZWZpUWsHPmxrUSe9wkTh263HbeZvRAG3dEE03rluUrf+CB/NVq+FLB9PNUhtYBHHoCPsIwfFOoL7GTqmCdGW34Da+weU3aL5rELYD2jTYO4tXeO4L0MuRJIEdlMF8Djw0VbYGnEq6Hg84JWnuqyVeaNCmtguxNREgTlmhz9bNJiBrYrp5c8LIR/rpgpsW6MYMuT628PAjdHghxGs7Da8YRi3CKUFighyf2bdI="
    secure: "YHWvVlx5wv2POltS4EfKtbI9PH0NKzv/ud1tNeFn7Zga5bi40jJ1Uqi1n+NfHYmIfhuTNh72VnVkieCcu9q2CSsbVArRAO8GTi82UD+MW+h4Pc4UjdqZVcD4DeY7txQKrrgtbG3qoEm4wT4wm3wAIgbi4uh/unGky7XrSSsVRyK4iR3KEn/WENMp+GcqVgv3d12A3diqq54HDaC9vSAKr3f0htYtuYKWbgQ2O6sBwZUph62S13nYumQAoCd+qEL/E11LH1ID/5xkXYF1ZbRYo/ojIZvgKP6mTq65ErJ2pgI5Sw+wtFYYyGWnLbZGFupqe5F0pRz9Tofbmj2HErkybXrb2CTAnuwM5s8ZGqEhga0Mdm7hx2kgBGOvj+ed34s7730cEd8vGdsZwgs+hZlLrs6g6uMnzKmCnpD9VgWKzuHWFrR6OxYnBUJ3CxTswgoChBqDcI7OvEj0Nj9cZ9F9x+i1QFefqU0uxho26y2A37Y8NszzwpOyT9oo4Zquzq2Dk6vzL9Eo/pK7XCTiYDD77EWYGAo1tU5xfkfZOxpOXbuWL38Cu4YosvfgUtoS5hzyEjxuGbVkAAqeK8OU6BumMVbUDvT0HNxku003aW3rzqhxeu0ERCUU5kAJJQkp/E274TRj63xjWH6HCjVsIHBf9AirqFttV0X/b0Lo21zGxR8="
    secure: "GVVDnPyrXS5BzGUpcJiOhIlCK89OMrW9C/DeSkniNsuXc2qoLpTIoTn0o/oaI8WNJXLUejtH2ncqtC3EdPp8RZ4Dj1HTEKU7TdwjKF04QQKWemt3WNNWSm6djwW9TG4Uig1jTaWm+ks1ykIKynQpmkgC4QP/UBlnAWmc4Zual0pXb7MaazyJCLXlQ3j3oH4O/wSCeh6VQntfrXblMAPsc5p3LNsc2qzP1rmdBtzQ5ZeOotUOdS4oo2XvOHiUXwRJawcIqpUaoqjCX39mkEXeR4NZpTWTqFOIT0UCF2YXtq9Mpo7t3zykxPVjhL8abLj+1x9meyRB3ARII79JRkn8Ad8h8oD7gh+U4PZ4+JkHFMFSr8796opMnJLpIXaZqHP7HAZkq6Z1cTmWMVCGAOQYbQLMFyMRC1KP0PuH4z0l5atiQneZ776gzXY4FMH5KCCXMyYiG2Q/6gXJtM/PNIoNn2qe1xk4ugVPONCJntuK5Ptkrsxz4qMod179nZKpKooJTfqfB5HkWE1+7XqxCXWWiBjlD/pPH0yVtdEdgwpjgnNoEjAy6gEKzW4CeT5Efp05PtgWB2ZPVWGfB+7v6WAu3qLj8H8c1Tb1/0uYICzPi7YP1Bn9SVx7/1kfkn8wgNQk6prLr71yiw4bWG7/ls1rvuQUd4wtRIspAn+sM2WjfrU="
before_install:
  - echo ${OBS_USER}
  - echo $OBS_USER
  - echo $TEST
  - echo ${TEST}
  - mkdir usr
  - if [ $TRAVIS_OS_NAME == osx ]; then . travis/before-install-osx.sh ; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then  . travis/before-install-linux.sh; fi
before_script:
  - echo $PKG_CONFIG_PATH
  - cmake -DCMAKE_INSTALL_PREFIX='./usr' .
script:
  - make
  - if [ $TRAVIS_OS_NAME == osx ]; then cpack -G OSXX11; fi
after_success:
  - if [ $TRAVIS_OS_NAME == linux ]; then . travis/deploy-obs.sh; fi
os:
  - osx
  - linux
deploy:
  provider: bintray
  file: "tools/bintray.json"
  user: "metaxy"
  on:
    branch: master
    condition: $TRAVIS_OS_NAME = osx  
  key:
    secure: PmBDMb8GJy1GhZ9QCM1p2Qx9A0W0hBvVJSrGFfyz+btngOwbrpNhj/l233HihLY5SmAM6h7yWCwt+jMhKJezr+kxTQSxhR+piM+ZJOeD7LcKeniHGsANHSvsIDY9rNM8gk4sBcUl6jxWEYxgqpuxF5UVIrVKa6IZGE/YkMJ8KqyLSMzKXRsmLoUmYK+KzhsAT2FIb1OZLcazGZ0tuI1PyoXqQL/nhxskRudMSflFzVWPhae03rg0J91GRVxTKeiMwPxfw+atdVpF7P7RxOXieyhZCqb3gkyO1/v7PU4G9LKEtrncdRyVhF8yE28JmjjpVeq7NgM0pvP1iJtI/jbwm6eFF5HnB+77JZfNn5gW580icvllnjQdeUBQ4T+iM1xWA8Cy/0uCPiAhuFesAkfNWH1YaLMQHISUrikeKIjeOUwd6Ld6+Pp5hWLlKrdF1xRLw+EWj7x3Zj25rZ7Vr/IhFo+cBmqqlNYZWxV09BZo1XpYQdB1XufmxJ/AAxetF7/vGKymE1k8+yLcAUcHLWht/Jc8KVhrGMpPWX1vP0ydHofLAA/lSKgADmmOj5I952gMl3/eeXgioXMSiJpIzQlzFnz+JbzsDqkhVYEfCJCybIU9/nyvR7J10H2dxp6f6e5dhjvOnKrFJ9iSIoJVIY0qdJpIv6Z4HlTRmUQpItfSYEw=
