language: cpp

compiler:
  - gcc

before_install:
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && xcode-select --install && brew install qt && brew install clucene ; fi

before_script:
  - cmake -DCMAKE_INSTALL_PREFIX='/usr' .

script: make

os:
  - osx