language: cpp
sudo: true
compiler:
  - gcc
env:
  global:
    - secure: "YHWvVlx5wv2POltS4EfKtbI9PH0NKzv/ud1tNeFn7Zga5bi40jJ1Uqi1n+NfHYmIfhuTNh72VnVkieCcu9q2CSsbVArRAO8GTi82UD+MW+h4Pc4UjdqZVcD4DeY7txQKrrgtbG3qoEm4wT4wm3wAIgbi4uh/unGky7XrSSsVRyK4iR3KEn/WENMp+GcqVgv3d12A3diqq54HDaC9vSAKr3f0htYtuYKWbgQ2O6sBwZUph62S13nYumQAoCd+qEL/E11LH1ID/5xkXYF1ZbRYo/ojIZvgKP6mTq65ErJ2pgI5Sw+wtFYYyGWnLbZGFupqe5F0pRz9Tofbmj2HErkybXrb2CTAnuwM5s8ZGqEhga0Mdm7hx2kgBGOvj+ed34s7730cEd8vGdsZwgs+hZlLrs6g6uMnzKmCnpD9VgWKzuHWFrR6OxYnBUJ3CxTswgoChBqDcI7OvEj0Nj9cZ9F9x+i1QFefqU0uxho26y2A37Y8NszzwpOyT9oo4Zquzq2Dk6vzL9Eo/pK7XCTiYDD77EWYGAo1tU5xfkfZOxpOXbuWL38Cu4YosvfgUtoS5hzyEjxuGbVkAAqeK8OU6BumMVbUDvT0HNxku003aW3rzqhxeu0ERCUU5kAJJQkp/E274TRj63xjWH6HCjVsIHBf9AirqFttV0X/b0Lo21zGxR8="
    - OBS_USER=metaxy
before_install:
  - mkdir usr
  - if [ $TRAVIS_OS_NAME == osx ]; then . travis/before-install-osx.sh ; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then  . travis/before-install-linux.sh; fi
before_script:
  - echo $PKG_CONFIG_PATH
  - cmake -DCMAKE_INSTALL_PREFIX='./usr' .
script:
  - make
  - if [ $TRAVIS_OS_NAME == osx ]; then cpack -G OSXX11; fi
after_success:
  - if [ $TRAVIS_OS_NAME == linux ]; then . travis/deploy-obs.sh; fi
os:
  - osx
  - linux
deploy:
  provider: bintray
  file: "tools/bintray.json"
  user: "metaxy"
  on:
    branch: master
    condition: $TRAVIS_OS_NAME = osx  
  key:
    secure: PmBDMb8GJy1GhZ9QCM1p2Qx9A0W0hBvVJSrGFfyz+btngOwbrpNhj/l233HihLY5SmAM6h7yWCwt+jMhKJezr+kxTQSxhR+piM+ZJOeD7LcKeniHGsANHSvsIDY9rNM8gk4sBcUl6jxWEYxgqpuxF5UVIrVKa6IZGE/YkMJ8KqyLSMzKXRsmLoUmYK+KzhsAT2FIb1OZLcazGZ0tuI1PyoXqQL/nhxskRudMSflFzVWPhae03rg0J91GRVxTKeiMwPxfw+atdVpF7P7RxOXieyhZCqb3gkyO1/v7PU4G9LKEtrncdRyVhF8yE28JmjjpVeq7NgM0pvP1iJtI/jbwm6eFF5HnB+77JZfNn5gW580icvllnjQdeUBQ4T+iM1xWA8Cy/0uCPiAhuFesAkfNWH1YaLMQHISUrikeKIjeOUwd6Ld6+Pp5hWLlKrdF1xRLw+EWj7x3Zj25rZ7Vr/IhFo+cBmqqlNYZWxV09BZo1XpYQdB1XufmxJ/AAxetF7/vGKymE1k8+yLcAUcHLWht/Jc8KVhrGMpPWX1vP0ydHofLAA/lSKgADmmOj5I952gMl3/eeXgioXMSiJpIzQlzFnz+JbzsDqkhVYEfCJCybIU9/nyvR7J10H2dxp6f6e5dhjvOnKrFJ9iSIoJVIY0qdJpIv6Z4HlTRmUQpItfSYEw=
