 
FIND_PATH(ZLIB_INCLUDE_DIR zlib.h.h /usr/include /usr/local/include)

FIND_LIBRARY(ZLIB_LIBRARY NAMES libz PATH /usr/lib /usr/local/lib /lib) 

IF (ZLIB_INCLUDE_DIR AND ZLIB_LIBRARY)
   SET(ZLIB_FOUND TRUE)
ENDIF (ZLIB_INCLUDE_DIR AND ZLIB_LIBRARY)


IF (ZLIB_FOUND)
   IF (NOT Zlib_FIND_QUIETLY)
      MESSAGE(STATUS "Found Zlib: ${ZLIB_LIBRARY}")
   ENDIF (NOT Zlib_FIND_QUIETLY)
ELSE (ZLIB_FOUND)
   IF (Zlib_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find Zlib")
   ENDIF (Zlib_FIND_REQUIRED)
ENDIF (ZLIB_FOUND)